config/routes.rb
Rails.application.routes.draw do
  # ログイン ログアウト
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"

  # トップページ
  root "home#index"

  # 開発・デバック用
  get "up", to: "rails/health#show", as: :rails_health_check
  get "service-worker", to: "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest", to: "rails/pwa#manifest", as: :pwa_manifest

  # user登録とフォーム送信用
  resources :users, only: %i[new create show index] do
    resources :battles,  only: %i[index] do
      collection do
        post "increase" # /users/id/battles/increase
        post "decrease"
        post "save_score"
        get :escape
      end
    end

    resources :monthly_goals, only: %i[new create edit update]
  end
end

app/models/battle.rb
class Battle < ApplicationRecord
  belongs_to :user
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  include FlashMessageHelper
  before_action :set_user
  before_action :initialize_session

  def index
    # 選択された日付を受け取る（なければ今日）
    # @selected_date = params[:date].present? ? Date.parse(params[:date]) : Date.current
    begin
      @selected_date = params[:date].present? ? Date.parse(params[:date]) : Date.current
    rescue ArgumentError
      @selected_date = Date.current
    end

    # セッションに日付を記録
    session[:last_selected_date] = @selected_date.to_s

    # dbに保管されている経験値の合計
    @base_experience = @user.scores.sum(:experience)

    # セッションの増減値
    session[:exp_diff] ||= 0

    # 表示用の最終経験値（DB+セッション値）
    @experience = @base_experience + session[:exp_diff]
    @experience = 0 if @experience < 0 # マイナスにならないために

    @level = (@experience / 8) + 1
    @next_level_exp = (@level * 8) - @experience
  end

  def increase
    # セッション初期化
    session[:exp_diff] ||= 0

    # DBの合計経験値（レベル計算の基準）
    base_exp = @user.scores.sum(:experience)
    previous_total_exp = base_exp + session[:exp_diff]

    # 経験値を +1
    session[:exp_diff] += 1
    new_total_exp = base_exp + session[:exp_diff]
    session[:experience] = 7984 if session[:experience] > 7984

    # レベル判定
    previous_level = (previous_total_exp / 8) + 1
    new_level = (new_total_exp / 8) + 1

    flash[:rpg] = ex_up_message

    if new_level > previous_level
      flash[:rpg2] = "ゆうしゃはレベルが上がった！"
      flash[:levelup] = true
    end

    redirect_to user_battles_path(@user, date: params[:date] || session[:last_selected_date])
  end

  def decrease
    # セッション初期化
    session[:exp_diff] ||= 0

    # 表示のためにdbから現在の合計経験値を取得
    base_exp = @user.scores.sum(:experience)
    previous_total_exp = base_exp + session[:exp_diff]

    session[:exp_diff] -= 1

    # 下限を 0 に保つ
    if (base_exp + session[:exp_diff]) < 0
      session[:exp_diff] = -base_exp
    end

    new_total_exp = base_exp + session[:exp_diff]

    previous_level = (previous_total_exp / 8) + 1
    new_level = (new_total_exp / 8) + 1

    flash[:rpg] = "ゆうしゃはなまけた<br>けいけんちが1下がった<br>"
    if new_level < previous_level

    flash[:rpg3] = lv_down_message
      flash[:leveldown] = true
    end

    redirect_to user_battles_path(@user, date: params[:date] || session[:last_selected_date])
  end

  def save_score
    recorded_on = params[:date].presence || session[:last_selected_date] || Date.current
    recorded_on = Date.parse(recorded_on.to_s)

    exp_diff = session[:exp_diff] || 0 # セッションに保存された増減値を使う

    Rails.logger.debug "[DEBUG] save_score: exp_diff=#{exp_diff}"

    return redirect_to user_path(@user) if exp_diff == 0

    base_exp = @user.scores.sum(:experience)
    exp_diff = -base_exp if base_exp + exp_diff < 0 # 合計値がマイナスにならないよう調整

    score = Score.find_or_initialize_by(user_id: @user.id, recorded_on: recorded_on)
    score.experience ||= 0
    score.experience += exp_diff

    if score.save

      Rails.logger.debug "[DEBUG] save_score: save successful"

      # セッションをリセット（必要に応じて）
      session[:exp_diff] = 0
      session[:last_selected_date] = nil
      redirect_to user_path(@user)
    else

      Rails.logger.debug "[DEBUG] save_score: save FAILED"

      redirect_to user_battles_path(@user, date: recorded_on)
    end
  end

  def escape
    # セッションの経験値差分をリセット（バトル画面からにげる）
    session[:exp_diff] = 0
    redirect_to user_path(@user, date: params[:date] || session[:last_selected_date])
  end

  private

  def initialize_session
    session[:experience] ||= 0
  end

  def set_user
    unless current_user
      flash[:danger] = "[警告] 不正なアクセスです"
      redirect_to root_path
      return
    end

    if params[:user_id].to_i != current_user.id
      flash[:danger] = "[警告] 不正なアクセスです"
      redirect_to root_path
    else
      @user = current_user
    end
  end
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/views/battles/index.html.erb
<!-- app/views/battles/index.html.erb -->
<!-- フラッシュメッセージの表示とStimulusコントローラの呼び出し -->
<% if flash[:rpg].present? %>
  <div
    data-controller="sound-change"
    <%= "data-sound-change-levelup-value='true'" if flash[:levelup] %>
    <%= "data-sound-change-leveldown-value='true'" if flash[:leveldown] %>
    class="flash-message"
  >
  </div>


<% end %>

<div class='status-window'>
  <p class='status-item'>勇者: <%= @user.name %></p>
  <p class='status-item'>レベル: <%= @level %> LV</p>
  <p class='status-item'>けいけんち: <%= @experience %> EX</p>
  <p class='status-item'>つぎのレベルまであと: <%= @next_level_exp %> EX </p>
</div>

<div class="enemy-container">
  <%= image_tag 'enemy_01.png', class: 'enemy-image' %>
</div>


<div class="battle-bottom-ui-wrapper" data-controller="window-toggle">
  <div class='battle-bottom-ui'>
  <!-- コマンドウインドウ -->
  <div class='battle-window' data-window-toggle-target="command">
    <%= link_to 'がんばった', increase_user_battles_path(date: @selected_date), method: :post, class: 'battle-command' %>
    <%= link_to 'なまけた', decrease_user_battles_path(date: @selected_date), method: :post, class: 'battle-command' %>
    <%= link_to 'セーブしてもどる', save_score_user_battles_path(date: @selected_date), method: :post, class: 'battle-command' %>
    <%= link_to 'にげる', escape_user_battles_path(@user, date: @selected_date), class: 'battle-command' %>
  </div>

  <!-- メッセージウインドウ(3秒で消えるフラッシュメッセージ) -->
  <div class="battle-message-window"
        data-controller="flash"
        data-flash-timeout-value="3000"
        data-action="flash:hide@window->window-toggle#showCommand"
        data-window-toggle-target="message">
    <% if flash[:rpg].present? %>
      <div data-flash-target="message">
        <%= flash[:rpg].html_safe %>
        <% if flash[:levelup] %>
          <%= flash[:rpg2] %>
        <% elsif flash[:leveldown] %>
          <%= flash[:rpg3].html_safe %>
        <% end %>
      </div>
    <% end %>

    <span data-flash-target="default" class="default-message" style="<%= flash[:rpg].present? ? 'display:none;' : '' %>">
      本日のかだいがあらわれた<br>自分できめた『ひょうかきじゅん』に合わせてコマンドを押そう
    </span>
  </div>
</div>